ci: modernize solaris config
test/contrib/isotp.uts is dropped to prevent the tests from failing with
```
━ UTScapy - Scapy 2.7.1rc1.post58 - 3.13.13
 └ Loaded config file ./test/configs/solaris.utsc
ERROR: Cannot remove test/contrib/isotp.uts from test files
```
It's a follow-up to 386d7fa4d811b35364ca325353123685ac84c4dd where that
file was removed.

TLS-related tests are adjusted
It's a follow-up to 219f2febd8456c440988b329b44c1dbcd0e47d0d where the
TLS tests were moved to test/scapy/layers/tls

scapy-rpc tests are added

AI-Assisted: no