ci: install cbor2 on Packit
to prevent the newly introduced CBOR tests from failing with:
```
 ###(090)=[failed] Interop: Large unsigned integer

 >>> large_int = 18446744073709551615  # 2^64 - 1
 >>> encoded = cbor2.dumps(large_int)
 NameError: name 'cbor2' is not defined
```
and so on.