Stun improvements (#4712)
* STUN: Fix building binding response

Building a binding success response with an XOR-MAPPED-ADDRESS attribute
filed with:
      File "/home/simon/src/scapy/scapy/contrib/stun.py", line 152, in i2m
        return struct.pack(">i", struct.unpack(">i", inet_aton(x)) ^ MAGIC_COOKIE)
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
    TypeError: While dissecting field 'attributes': While dissecting field 'xip': unsupported operand type(s) for ^: 'tuple' and 'int'

Fixed by properly handling the return value of struct.unpack (a tuple
with one int).

* STUN: Support IPv6 in binding response

The XOR-MAPPED-ADDRESS attribute can contain either IPv4 or IPv6
addresses in the xip field. The address_family field selects the type of
the xip field.

* STUN: Support MAPPED-ADDRESS attribute

Even RFC 8489 compliant STUN servers respond with the non-XORed
MAPPED-ADDRESS attribute, if the magic cookie in the request doesn't
have the expected value.

* STUN: Fix UDP/TCP layer binding

STUN responses weren't properly dissected, because the protocol was only
bound to the destination port. Fixed by binding both source and
destination port number 3478 to the STUN protocol. Also set both port
numbers when building messages, otherwise the UDP/TCP default source
port (DNS / FTP) would be used.