[SSLv2] s/debug_dissect/debug_dissector/
to prevent do_dissect_payload from failing with
```
  File "scapy/scapy/layers/tls/record_sslv2.py", line 177, in do_dissect_payload
    if conf.debug_dissect:
       ^^^^^^^^^^^^^^^^^^
  File "scapy/scapy/config.py", line 950, in __getattribute__
    return object.__getattribute__(self, attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Conf' object has no attribute 'debug_dissect'
```

The test is added to exercise the Exception clause.