Fix deprecated code examples in usage.rst
The code examples in the documentation resolves in: "TypeError: <lambda>() missing 1 required positional argument: 'r'".
This is because "PEP 3113 -- Removal of Tuple Parameter Unpacking". for more info see https://www.python.org/dev/peps/pep-3113/.
This commit updates the docs to resolve this issue.
Additionaly, it fixes a minor mistake found at line 387.