Change type of Packet.fields_desc to a Sequence
Sequences in mypy allow variance, so we can assign lists
of Field subtypes to fields_desc.

This is needed for the scapy.layers.l2.Loopback class, which
attempts to assign fields_desc twice with different types. Without this change,
we get the following mypy errors:

    scapy/layers/l2.py:620: error: Incompatible types in assignment (expression has type "List[IntEnumField]", base class "Packet" defined the type as "List[Union[Field[Any, Any], _FieldContainer]]")
    scapy/layers/l2.py:620: note: "List" is invariant -- see http://mypy.readthedocs.io/en/latest/common_issues.html#variance
    scapy/layers/l2.py:620: note: Consider using "Sequence" instead, which is covariant