No longer include LLTD hostnames in format strings
to prevent sprintf from trying to parse them.

Fixes:
```
  File "scapy/sendrecv.py", line 1439, in tshark
  File "scapy/sendrecv.py", line 1311, in sniff
  File "scapy/sendrecv.py", line 1254, in _run
  File "scapy/sessions.py", line 109, in on_packet_received
  File "scapy/sendrecv.py", line 1436, in _cb
  File "scapy/packet.py", line 1645, in summary
  File "scapy/packet.py", line 1619, in _do_summary
  File "scapy/packet.py", line 1619, in _do_summary
  File "scapy/packet.py", line 1619, in _do_summary
  [Previous line repeated 6 more times]
  File "scapy/packet.py", line 1622, in _do_summary
  File "scapy/layers/lltd.py", line 718, in mysummary
    return (self.sprintf("Hostname: %r" % self.hostname),
  File "scapy/packet.py", line 1530, in sprintf
    j = fmt[i + 1:].index("}")
ValueError: substring not found
```