Look for flag values instead of flag fields
to prevent .command() from producing invalid commands containing
something like `<Flag 15 ...>`.

When flag fields are embedded into other fields they can't be
recognized by looking at their type without following the "fld" chain.
Their values are always FlagValues though so this check can be used
instead.

Fixes:
```
p = CondFlagsTest(b"\x00\x0f")
assert p == eval(p.command())
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "<string>", line 1
    CondFlagsTest(b=0, f=<Flag 15 (????)>)
                         ^
SyntaxError: invalid syntax
```

It's a follow-up to a0fd8688dc405799b676e21d7a0741512ad9aca1