Tolerate non-UTF-8 NetBIOS names in NetBIOS answering machines (#4007)
NetBIOS names encoded using non-UTF-8 encodings can't be
decoded without specifying them explicitly (and for that to work they
have to be inferred based on bytes). It's kind of possible but instead
of guessing encodings `is_request` uses raw question names and `server_name` is
converted to bytes instead. To make it possible to spoof all sorts of
hosts NBNS_am also accepts bytes as server_names directly (but the patch is
backward-compatible with the previous versions accepting strings only).
Empty strings and Nones are still equivalent and keep working too.

Fixes:
```
  File "scapy/ansmachine.py", line 57, in <lambda>
  File "scapy/ansmachine.py", line 211, in __call__
  File "scapy/ansmachine.py", line 217, in sniff
  File "scapy/sendrecv.py", line 1311, in sniff
  File "scapy/sendrecv.py", line 1254, in _run
  File "scapy/sessions.py", line 109, in on_packet_received
  File "scapy/ansmachine.py", line 167, in reply
  File "scapy/layers/netbios.py", line 381, in is_request
    req[NBNSQueryRequest].QUESTION_NAME.decode().strip() ==
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 0: invalid continuation byte
```