ci: install scapy-rpc on Packit
to prevent the tests from failing with
```
 ###(000)=[failed] [C706 MGMT] - Import layer
 ...
 ModuleNotFoundError: No module named 'scapy.layers.msrpce.raw.mgmt'

 ###(001)=[failed] [C706 MGMT] - Dissect rpc__mgmt_inq_if_ids_Response
 ...
 >>> pkt = rpc__mgmt_inq_if_ids_Response(DATA)
 NameError: name 'rpc__mgmt_inq_if_ids_Response' is not defined
```

scapy-rpc isn't packaged so it has to be installed using pip instead of
Build-Requires as usual.

It's a follow-up to https://github.com/secdev/scapy/pull/4921.