Make RawVal work with all field types (fix for issue #3691)
Using RawVal with certain field types, e.g. FixedPointField,
fails with a TypeError like the one below:

>>> NTP(orig=RawVal(b"\xe6}gt\x00\x00\x00\x00"))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File /home/user/.local/lib/python3.8/site-packages/IPython/core/formatters.py:707, in PlainTextFormatter.__call__(self, obj)
    700 stream = StringIO()
    701 printer = pretty.RepresentationPrinter(stream, self.verbose,
    702     self.max_width, self.newline,
    703     max_seq_length=self.max_seq_length,
    704     singleton_pprinters=self.singleton_printers,
    705     type_pprinters=self.type_printers,
    706     deferred_pprinters=self.deferred_printers)
--> 707 printer.pretty(obj)
    708 printer.flush()
    709 return stream.getvalue()

File /home/user/.local/lib/python3.8/site-packages/IPython/lib/pretty.py:410, in RepresentationPrinter.pretty(self, obj)
    407                         return meth(obj, self, cycle)
    408                 if cls is not object \
    409                         and callable(cls.__dict__.get('__repr__')):
--> 410                     return _repr_pprint(obj, self, cycle)
    412     return _default_pprint(obj, self, cycle)
    413 finally:

File /home/user/.local/lib/python3.8/site-packages/IPython/lib/pretty.py:778, in _repr_pprint(obj, p, cycle)
    776 """A pprint that just redirects to the normal repr function."""
    777 # Find newlines and replace them with p.break_()
--> 778 output = repr(obj)
    779 lines = output.splitlines()
    780 with p.group():

File /home/user/.local/lib/python3.8/site-packages/scapy/packet.py:533, in Packet.__repr__(self)
    531     if isinstance(fval, (list, dict, set)) and len(fval) == 0:
    532         continue
--> 533     val = f.i2repr(self, fval)
    534 elif f.name in self.overloaded_fields:
    535     fover = self.overloaded_fields[f.name]

File /home/user/.local/lib/python3.8/site-packages/scapy/layers/ntp.py:80, in TimeStampField.i2repr(self, pkt, val)
     78 if val is None:
     79     return "--"
---> 80 val = self.i2h(pkt, val)
     81 if val < _NTP_BASETIME:
     82     return val

File /home/user/.local/lib/python3.8/site-packages/scapy/fields.py:3044, in FixedPointField.i2h(self, pkt, val)
   3041 def i2h(self, pkt, val):
   3042     # type: (Optional[Packet], int) -> EDecimal
   3043     # A bit of trickery to get precise floats
-> 3044     int_part = val >> self.frac_bits
   3045     pw = 2.0**self.frac_bits
   3046     frac_part = EDecimal(val & (1 << self.frac_bits) - 1)

TypeError: unsupported operand type(s) for >>: 'RawVal' and 'int'

The root cause is that the field's `any2i()` or `i2h()` methods
may be expecting a certain value type instead of RawVal. To fix
this, we check if the value is a RawVal before calling either of
those methods. Doing this in packet.py saves us from having to do
it in ALL `any2i()` and `i2h()` methods (at least the ones which
fail when given a RawVal).