Turn PIMv2HelloLANPruneDelayValue.t into BitField
to make its repr work.

It's just one bit so FlagsField isn't suitable there.

Fixes:
```
>>> repr(PIMv2HelloLANPruneDelayValue(t=1))
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "scapy/packet.py", line 563, in __repr__
    val = f.i2repr(self, fval)
          ^^^^^^^^^^^^^^^^^^^^
  File "scapy/fields.py", line 3092, in i2repr
    return "None" if x is None else str(self._fixup_val(x))
                                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "scapy/fields.py", line 2947, in __str__
    return ("+" if self.multi else "").join(r)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, int found
```

It's a follow-up to 6e205b21608f1672a01ce2e186526fd117ac7397