Results.plot callback receive 2 args: (query,answer)
Fixes:

```python
>>> a.plot(lambda x:x[1].id)
File /home/isidro/ms/webserver/venv/lib/python3.13/site-packages/scapy/plist.py:288, in _PacketList.plot(self, f, lfilter, plot_xy, **kargs)
    286 # Get the list of packets
    287 if lfilter is None:
--> 288     lst_pkts = [f(*e) for e in self.res]
    289 else:
    290     lst_pkts = [f(*e) for e in self.res if lfilter(*e)]

TypeError: <lambda>() takes 1 positional argument but 2 were given
```