Parse zero-length DHCP options as well
Until 0db2a8cfb02195e6bba777ef9794fd33e605f11f was merged zero-length
DHCP options were parsed at least once and the "options" list contained
tuples with at least two elements. This patch restores that.

It prevents `repr(DHCP(...))` from crashing with something like
```
TypeError: ord() expected a character, but string of length 23 found
```
and also lets the fields with meaningfull empty values to be initialized
properly. For example,
```
>>> DHCP(b"\x79\x00").options
[('classless_static_routes',)]
```
turns into
```
[("classless_static_routes", [])]
```

It's a follow-up to 0db2a8cfb02195e6bba777ef9794fd33e605f11f