No longer include DNSSLs in format strings
to prevent sprintf from trying to parse them. ICMPv6NDOptRDNSS.mysummary
was changed too even though special characters should never get past
inet_pton and reach sprintf there.

It's a follow-up to f2a137c0388494318662b19f7082b492c7c22fca.

Fixes:
```
  File "scapy/sendrecv.py", line 1439, in tshark
  File "scapy/sendrecv.py", line 1311, in sniff
  File "scapy/sendrecv.py", line 1254, in _run
  File "scapy/sessions.py", line 109, in on_packet_received
  File "scapy/sendrecv.py", line 1436, in _cb
  File "scapy/packet.py", line 1645, in summary
  File "scapy/packet.py", line 1619, in _do_summary
  File "scapy/packet.py", line 1619, in _do_summary
  File "scapy/packet.py", line 1619, in _do_summary
  [Previous line repeated 2 more times]
  File "scapy/packet.py", line 1622, in _do_summary
  File "scapy/layers/inet6.py", line 2052, in mysummary
  File "scapy/packet.py", line 1530, in sprintf
    j = fmt[i + 1:].index("}")
        ^^^^^^^^^^^^^^^^^^^^^^
ValueError: substring not found
```