ci: drop downstream import check (#4988)
to prevent it from interfering with the upstream CI.

The import check was added recently in
https://src.fedoraproject.org/rpms/scapy/c/878585466261f17c01516a653d19cf47022c2f9f?branch=rawhide
and it started failing when https://github.com/secdev/scapy/pull/4975
was merged with
```
+ /usr/bin/python3 -sP /usr/lib/rpm/redhat/import_all_modules.py \
  -f /builddir/build/BUILD/scapy-2.7.0-build/scapy-2.7.0-1.20260423030854887593.pr2.57.g5d1727ff.fc43.x86_64-pyproject-modules \
  -e scapy.arch.bpf.core -e scapy.arch.bpf.supersocket -e scapy.arch.windows \
  -e scapy.arch.windows.native -e scapy.arch.windows.structures \
  -e scapy.contrib.cansocket_python_can -e scapy.tools.generate_bluetooth \
  -e scapy.tools.generate_ethertypes -e scapy.tools.generate_manuf \
  -e scapy.tools.scapy_pyannotate -e scapy.libs.winpcapy
...
...
  File "/builddir/build/BUILD/scapy-2.7.0-build/BUILDROOT/usr/lib/python3.14/site-packages/scapy/arch/windows/__init__.py", line 18, in <module>
    import winreg
ModuleNotFoundError: No module named 'winreg'
```
Since it can't keep up with upstream PRs it can be trimmed.

Big endian builds are back to normal
(https://forge.fedoraproject.org/infra/ansible/pulls/3316) and left
intact.

Closes https://github.com/secdev/scapy/issues/4979