Make repr(RadioTap) with the hemuou_per_user_known field work
Looks like it was a typo because FlagsFields expect lists, strings or
dicts to be passed to them.

Fixes:
```
Traceback (most recent call last):
  ...
  File "/home/vagrant/scapy-2/scapy/packet.py", line 563, in __repr__
    val = f.i2repr(self, fval)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/scapy-2/scapy/fields.py", line 3082, in i2repr
    return "None" if x is None else str(self._fixup_val(x))
                                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/scapy-2/scapy/fields.py", line 2931, in __str__
    name = self.names[i]
           ~~~~~~~~~~^^^
TypeError: 'set' object is not subscriptable
```

It's a follow-up to 76a88dacfcfed7308a316acd14136b5e6fb8ea52