setup.cfg: Add PEP 561 py.typed marker
This is required in order to use mypy with scapy annotations in a
dependent project. Otherwise you get messages like these:

error: Skipping analyzing "scapy.packet": module is installed, but missing library stubs or py.typed marker  [import-untyped]