libpcap: pass positive BIOCIMMEDIATE to ioctl
to prevent ioctl from failing with
```
 14115  14115 python3  CALL  ioctl(3,0xffffffff80044270,0x7f7fff1415b0)
 14115  14115 python3  GIO   fd 3 wrote 4 bytes
       "\^A\0\0\0"
 14115  14115 python3  RET   ioctl -1 errno 22 Invalid argument
```
and actually turn on immediate mode on 64-bit NetBSD machines.

With this patch applied tests waiting for timely replies
receive those replies in time in libpcap mode.

The negative value was most likely used to get around a bug in Python
2.4 where ioctl failed with
```
OverflowError: signed integer is greater than maximum
```
when the positive value was passed instead. That bug was fixed in Python
2.5 in https://bugs.python.org/issue1231069 and scapy no longer supports
Python 2 anyway.

AI-Assisted: no